#!/usr/bin/env bash
set -e

# Run from the IsaacLab repository root.
# Replace POLICY_CKPT with the checkpoint generated by train_robomimic_bc.sh.

POLICY_CKPT=${1:-./logs/robomimic/stack_cube_bc/model.pt}

./isaaclab.sh -p scripts/imitation_learning/robomimic/play.py \
  --task Isaac-Stack-Cube-Franka-IK-Rel-v0 \
  --checkpoint "$POLICY_CKPT"

