"""add_job_number_column

Revision ID: 53b08ee59659
Revises: 7d281eb59df1
Create Date: 2026-03-05 12:24:18.201304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53b08ee59659'
down_revision: Union[str, None] = '7d281eb59df1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hdf5_datasets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False, comment='文件名'),
    sa.Column('project', sa.String(), nullable=True, comment='项目'),
    sa.Column('task', sa.String(), nullable=True, comment='任务'),
    sa.Column('device', sa.String(), nullable=True, comment='机器人/设备'),
    sa.Column('uploader', sa.String(), nullable=True, comment='上传者（已废弃，保留兼容）'),
    sa.Column('source', sa.String(), nullable=True, comment='来源: local/collect/label/convert'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='入库时间'),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False, comment='文件大小（字节）'),
    sa.Column('duration_sec', sa.Float(), nullable=True, comment='时长（秒）'),
    sa.Column('format', sa.String(), nullable=False, comment='格式'),
    sa.Column('storage_type', sa.String(), nullable=False, comment='存储类型'),
    sa.Column('storage_uri', sa.String(), nullable=False, comment='文件绝对路径'),
    sa.Column('qc_status', sa.String(), nullable=False, comment='质检状态: pending/passed/failed'),
    sa.Column('label_status', sa.String(), nullable=False, comment='标注状态: unlabeled/labeled/partial'),
    sa.Column('assign_status', sa.String(), nullable=False, comment='分配状态: unassigned/assigned'),
    sa.Column('tags', sa.String(), nullable=True, comment='标签（逗号分隔）'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_uri')
    )
    op.create_index('idx_created_at', 'hdf5_datasets', ['created_at'], unique=False)
    op.create_index('idx_device', 'hdf5_datasets', ['device'], unique=False)
    op.create_index('idx_name', 'hdf5_datasets', ['name'], unique=False)
    op.create_index('idx_status', 'hdf5_datasets', ['qc_status', 'label_status', 'assign_status'], unique=False)
    op.create_index('idx_storage_uri', 'hdf5_datasets', ['storage_uri'], unique=False)
    op.alter_column('datasets', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.add_column('jobs', sa.Column('job_number', sa.Integer(), nullable=False))
    op.alter_column('jobs', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('jobs', 'task_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('runs', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('runs', 'task_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('tasks', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('runs', 'task_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('runs', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('jobs', 'task_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('jobs', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('jobs', 'job_number')
    op.alter_column('datasets', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_index('idx_storage_uri', table_name='hdf5_datasets')
    op.drop_index('idx_status', table_name='hdf5_datasets')
    op.drop_index('idx_name', table_name='hdf5_datasets')
    op.drop_index('idx_device', table_name='hdf5_datasets')
    op.drop_index('idx_created_at', table_name='hdf5_datasets')
    op.drop_table('hdf5_datasets')
    # ### end Alembic commands ###
